name: CI
on:
  pull_request:
    types: [labeled]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Run a one-line script
        if: contains(github.event.pull_request.labels.*.name, 'test')
        run: echo Hello, world!
